language: python

notifications:
    email: false

python:
    - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - deps='pip numpy scipy nose pep8 pystan progressbar prettytensor'
    - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps 
    - source activate test-environment
    - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
    - pip install python-coveralls
    - pip install numpydoc

install:
    - pip install -e .

before_script:
    - pep8 mir_eval tests evaluators

script:
    - nosetests -v --with-coverage --cover-package=mir_eval
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar

after_success:
    - coveralls
