site_name: Edward
theme: alabaster
docs_dir: .
repo_url: http://github.com/blei-lab/edward
site_url: http://edwardlib.org/
site_description: 'A library for probabilistic modeling, inference, and criticism.'

pages:
- Home: index.md
