site_name: Edward
docs_dir: .
theme_dir: 'theme'
repo_url: http://github.com/blei-lab/edward
site_url: http://edwardlib.org/

pages:
- Home: index.md
- Tutorial: tutorial.md
- Tutorial for Research: tutorial_research.md
- Design and Philosophy: design.md
- Developer Process: developer.md
- TensorFlow: tensorflow.md
- Feature Wishlist: wishlist.md
- Miscellaneous: misc.md

extra:
  logo: edward.png
  logo_name: true
  show_powered_by: false
  include_toc: false
  site_description: 'A library for probabilistic modeling, inference, and criticism.'
