site_name: Edward
docs_dir: source
theme_dir: 'theme'
repo_url: http://github.com/blei-lab/edward
site_url: http://edwardlib.org/

pages:
- Home: index.md
- Getting Started: getting-started.md
- Delving In: delving-in.md
- How To: how-to.md
- Advanced:  
    - Design and Philosophy: advanced/design.md
    - Guide for Research: advanced/guide-research.md
    - Developer Process: advanced/developer.md
    - Feature Wishlist: advanced/wishlist.md
    - API: advanced/api.md
- Miscellaneous: misc.md

extra:
  logo: edward.png
  logo_name: true
  show_powered_by: false
  include_toc: false
  site_description: 'A library for probabilistic modeling, inference, and criticism.'
